#!/bin/bash

# $IMAGE_NAME var is injected into the build so the tag is correct.

echo "Build hook running"
echo "Tags being built: $DOCKER_TAG"

IFS=',' read -ra tags <<< "$DOCKER_TAG"
TAG_COMMAND=""

for tag in "${tags[@]}"
do
    TAG_COMMAND="$TAG_COMMAND -t $DOCKER_REPO:$tag"
done

echo "Tagging with: $TAG_COMMAND"

docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --build-arg VCS_REF=`git rev-parse --short HEAD` \
             $TAG_COMMAND .